[workspace]
members = [
    "abi",
    "api",
    "cache",
    "msg_server",
    "cmd",
    "oss",
    "utils",
    "msg_gateway",
]
resolver = "2"
default-members = ["cmd"]

[profile.dev]
incremental = true
