component: all # all, api, ws, rpc, db, pusher
log:
  level: debug
  output: console

db:
  postgres:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    database: im
  mongodb:
    host: 127.0.0.1
    port: 27017
    user:
    password:
    database: im
  xdb: ./api/fixtures/xdb/ip2region.xdb

server:
  host: 127.0.0.1
  port: 50001
  jwt_secret: sandcat
  ws_lb_strategy: RoundRobin # Random, RoundRobin
  oauth2:
    - tp: google
      client_id: 1234567890
      client_secret: 1234567890
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
    - tp: github
      client_id: 1234567890
      client_secret: 1234567890
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token

service_center:
  host: 127.0.0.1
  port: 8500
  timeout: 5000
  protocol: http

websocket:
  protocol: ws
  host: 127.0.0.1
  port: 50000
  name: websocket
  tags:
    - websocket
    - grpc


rpc:
  health_check: false # no need to start the health check under dev mode
  ws:
    protocol: http
    host: 127.0.0.1
    port: 50002
    name: ws
    tags:
      - ws
      - grpc
    grpc_health_check:
      grpc_use_tls: false
      interval: 30 # second
  chat:
    protocol: http
    host: 127.0.0.1
    port: 50003
    name: chat
    tags:
      - chat
      - grpc
    grpc_health_check:
      grpc_use_tls: false
      interval: 30000 # second
  db:
    protocol: http
    host: 127.0.0.1
    port: 50004
    name: db
    tags:
      - db
      - grpc
    grpc_health_check:
      grpc_use_tls: false
      interval: 30000 # second
  pusher:
    protocol: http
    host: 127.0.0.1
    port: 50005
    name: pusher
    tags:
      - pusher
      - grpc
    grpc_health_check:
      grpc_use_tls: false
      interval: 30000 # second

redis:
  host: 127.0.0.1
  port: 6379
  seq_step: 10000

kafka:
  hosts:
    - 127.0.0.1:9092
  topic: sandcat-chat
  group: chat
  connect_timeout: 5000 # milliseconds
  producer:
    timeout: 3000
    acks: all # 0: no response, 1: leader response, all: all response
    max_retry: 3
    retry_interval: 1000 # retry interval in milliseconds
  consumer:
    auto_offset_reset: earliest # earliest, latest
    session_timeout: 20000


oss:
  endpoint: http://127.0.0.1:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: sandcat
  avatar_bucket: sandcat-avatar
  region: us-east-1

mail:
  # server: smtp.qq.com
  server: 127.0.0.1
  account: sandcat@sandcat.com
  # password: rxkhmcpjgigsbegi
  password: sandcat.email.password!~
  temp_path: ./api/fixtures/templates/*
  temp_file: email_temp.html
