services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  synapse:
    image: xuxiaomeng/synapse:latest
    container_name: synapse
    ports:
      - "8500:8500"
    environment:
      - SERVICE_ADDRESS=0.0.0.0:8500
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=im
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000' # 将MinIO API端口映射到主机的9000端口
      - '9001:9001' # 将MinIO Console管理界面映射到主机的9001端口
    environment:
      MINIO_ROOT_USER: minioadmin # 最新的MinIO版本中推荐使用MINIO_ROOT_USER和MINIO_ROOT_PASSWORD
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001" # 添加控制台地址的映射
    volumes:
      - 'miniodata:/data'
volumes:
  mongodata:
  miniodata:
  postgres_data:
