name: Rust Checks

on: [push, pull_request]

jobs:
  rust_checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Install clippy
        run: rustup component add clippy

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
            version: "23.x"

      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install -y librdkafka-dev

      - name: Check formatting with rustfmt
        run: cargo fmt -- --check

      - name: Check the package with cargo check
        run: cargo check --no-default-features --features=static

      - name: Lint with cargo clippy
        run: cargo clippy --all-targets --no-default-features --features=static --tests --benches -- -D warnings
