[package]
name = "abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
chrono = { version = "0.4.34", features = ["serde"] }
prost = "0.12.3"
prost-types = "0.12.3"
tonic = { version = "0.11.0", features = ["gzip"] }
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "uuid",
] }
thiserror = "1.0.57"
regex = "1.10.3"
derive_builder = "0.20.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.32"
axum = "0.7.4"
serde_json = "1.0.114"
tokio = "1.36.0"
mongodb = "2.8.2"
redis = { version = "0.25.2", features = ["tokio-comp"] }
[build-dependencies]
tonic-build = "0.11.0"
